### ISSUE TITLE
gbk 问题

### ISSUE THREAD

**Issue by WebLeader** [kingname/RemoteControl#2]
F:\work\Python\RemoteControl\mcc>python auto.py
Traceback (most recent call last):
  File "auto.py", line 58, in <module>
    mcc = MCC()
  File "auto.py", line 37, in __init__
    self.mailHelper = mailHelper()
  File "F:\work\Python\RemoteControl\mcc\utils\mailHelper.py", line 15, in __init__
    cfReader = ConfigReader(self.CONFIGPATH)
  File "F:\work\Python\RemoteControl\mcc\utils\configReader.py", line 9, in __init__
    self.cReader.read(configFile)
  File "C:\Python27\lib\site-packages\backports\configparser\__init__.py", line 705, in read
    self._read(fp, filename)
  File "C:\Python27\lib\site-packages\backports\configparser\__init__.py", line 1035, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode bytes in position 229-230: illegal multibyte sequence

**Comment by kingname** [comment]
请使用Python 3运行代码。

**Comment by WebLeader** [comment]
但是我有python3.7运行，在安装py2exe 报错python version 2.7 required,which was

**Comment by WebLeader** [comment]
我用3.6的python 也还是报错
F:\work\Python\RemoteControl\mcc>python auto.py
Traceback (most recent call last):
  File "auto.py", line 58, in <module>
    mcc = MCC()
  File "auto.py", line 37, in __init__
    self.mailHelper = mailHelper()
  File "F:\work\Python\RemoteControl\mcc\utils\mailHelper.py", line 15, in __init__
    cfReader = ConfigReader(self.CONFIGPATH)
  File "F:\work\Python\RemoteControl\mcc\utils\configReader.py", line 9, in __init__
    self.cReader.read(configFile)
  File "C:\Python\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Python\lib\configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 229: illegal multibyte sequence

**Comment by kingname** [comment]
这就非常奇怪了。

你改一下代码：mcc/utils/configReader.py把第9行改为

```python
self.cReader.read(configFile, encoding='utf-8')
```

然后再试一试。

另外，如果你不是做木马，只是自己用的话，没有必要把它编译成exe文件。直接用Python跑就可以了。

**Comment by kingname** [comment]
这个代码是我三年前为极客学院的一个课程做的实例代码，如果你想了解细节的话，可以看Readme下面提供的课程视频。

如果你觉得这个代码有用的话可以告诉我，我可以重构一下。

**Comment by WebLeader** [comment]
做木马，py2exe，去哪里下载？3.6版本的？   视频我看过了，能加下你微信吗？我是刚刚开始学习python

**Comment by kingname** [comment]
在我的印象里面，py2exe不太好用。pyinstaller更好用一些。关于做木马，其实我不建议用邮件控制，你看看另外两个，一个是有网页界面的，还有一个是有桌面UI的。我建议用用桌面UI的：https://github.com/kingname/RemoteControl/tree/master/uiControl。

在这个代码里面我用的是Python 2和wxPython，但是三年过去了，时代已经大不一样。Python 2已经成为了历史，Python 3才是未来。所以我已经不建议用wxPython做图形界面了。

如果用Python 3的话，你可以看懂逻辑以后用系统自带的tkinter来重写图形界面。

由于你是用于不正当用途，所以我出于不禁止不提倡的的角度，不会给你更多指导，你需要自己去研究。

**Comment by WebLeader** [comment]
我是刚刚入门，先了解配置，和运行。可以运行了，多谢！      我不是用在不正当途径，只是看能不能运行
